# Generated by Django 4.2.5 on 2024-11-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserActionLog",),
    ]
